title: Ocean Biodiversity Information System
email: helpdesk@obis.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-get-json

jekyll_get_json:
  - data: nodes
    json: "https://api.obis.org/node"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  data_products:
    output: true
  projects:
    output: false
  usecases:
    output: true

menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
  - title: "Resources"
    subitems:
    - title: "Data Products"
      url: "/products/"
    - title: "Projects"
      url: "/projects/"
