title: Ocean Biodiversity Information System
email: helpdesk@obis.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-get-json

jekyll_get_json:
  - data: nodes
    json: "https://api.obis.org/node"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
  - nginx
  - docker-compose.yml

collections:
  data_products:
    output: true
  projects:
    output: false
  usecases:
    output: true

menu:
  - title: "Who we are"
    subitems:
    - title: "Vision and mission"
      url: "/about/visionmission"
    - title: "Nodes"
      url: "/about/nodes"
    - title: "Governance"
      url: "/about/governance"
    - title: "Team and contatcs"
      url: "/contact"
    - title: "Become a partner"
      url: "/about/partner"
  - title: "What we do"
    subitems:
    - title: "Core activities"
      url: "/whatwedo/core-activities"
    - title: "Impact"
      url: "/whatwedo/impact"
    - title: "Objectives"
      url: "/whatwedo/objectives"
