title: Ocean Biodiversity Information System
email: helpdesk@obis.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
collections:
  data_products:
    output: true
  projects:
    output: false

menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Resources"
    subitems:
    - title: "Data Products"
      url: "/products/"
    - title: "Projects"
      url: "/projects/"
