title: Your awesome title
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

exclude:
  - README.md

collections:
  data_products:
    output: true
  projects:
    output: false

menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Resources"
    subitems:
    - title: "Data Products"
      url: "/products/"
    - title: "Projects"
      url: "/projects/"
