version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: sh -c "jekyll build && jekyll serve --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
      - ./_site:/srv/jekyll/_site
    environment:
      - JEKYLL_ENV=production
      - JEKYLL_URL=${SITE_URL:-https://obis.org}

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    volumes:
      - ./fastapi:/app
      - ./_site:/app/static  # Serve shared assets
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf