version: '3.8'

services:
  build:
    image: jekyll/jekyll:latest
    command: jekyll build
    environment:
      - JEKYLL_ENV=production
    volumes:
      - ./:/srv/jekyll
      - ./_site:/srv/jekyll/_site

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    volumes:
      - ./fastapi:/app
      - ./_site:/app/static  # Serve shared assets
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./_site:/usr/share/nginx/html  # Serve Jekyll static files
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - build