version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --livereload --host 0.0.0.0
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/srv/jekyll
      - ./_site:/srv/jekyll/_site

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    volumes:
      - ./fastapi:/app
      - ./_site:/app/static  # Serve shared assets
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf